# Azure DevOps Pipeline for DataModelViewer (Reusable Template)
#
# This pipeline is intended to be copied to other Azure DevOps projects.
# It clones the public DataModelViewer repository and runs the build and deploy steps
# using the shared templates (azure-pipelines-build-jobs.yml and azure-pipelines-deploy-jobs.yml).
#
# USAGE:
# 1. Copy this file and the two job templates to your Azure DevOps repo.
# 2. Set up the required variable group and service connection in your Azure DevOps project.
# 3. Adjust the parameters below as needed for your environment.
#
# Required variables (set as pipeline variables or variable group):
#   - AzureServiceConnectionName
#   - AzureResourceGroupName
#   - AzureLocation
#   - WebsitePassword
#   - WebsiteSessionSecret
#   - WebsiteName
#   - AzureTenantId
#   - AzureClientId
#   - AzureClientSecret
#   - DataverseUrl
#   - AdoWikiName
#   - AdoWikiPagePath
#   - AdoRepositoryName
#   - EntraIdAllowedGroups

trigger: none
pr: none
schedules:
  - cron: "0 3 * * *"
    displayName: Daily build at 03:00 AM
    always: true
    branches:
      include:
        - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: "DataModel"  # Change this to your variable group name if needed
  - name: bicepTemplateFile
    value: "Infrastructure/main.bicep"

resources:
  repositories:
  - repository: wiki
    type: git
    name: Documentation  # Change this to correct repo if needed

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: BuildApp
        uses:
          repositories:
            - wiki
        displayName: "Build App"
        steps:
          - checkout: none
          - script: |
              git clone https://github.com/delegateas/DataModelViewer.git $(Build.SourcesDirectory)
            displayName: "Clone DataModelViewer public repository"
          - template: azure-pipelines-build-jobs.yml
            parameters:
              bicepTemplateFile: $(bicepTemplateFile)
              azureTenantId: $(AzureTenantId)
              azureClientId: $(AzureClientId)
              azureClientSecret: $(AzureClientSecret)
              dataverseUrl: $(DataverseUrl)
              adoWikiName: $(AdoWikiName)
              adoWikiPagePath: $(AdoWikiPagePath)

  - stage: Deploy
    displayName: "Deploy Stage"
    dependsOn: Build
    jobs:
      - job: DeployApp
        displayName: "Deploy App"
        steps:
          - checkout: none
          - script: |
              git clone https://github.com/delegateas/DataModelViewer.git $(Build.SourcesDirectory)
            displayName: "Clone DataModelViewer public repository"
          - template: azure-pipelines-deploy-jobs.yml
            parameters:
              bicepTemplateFile: $(bicepTemplateFile)
              azureServiceConnectionName: $(AzureServiceConnectionName)
              azureResourceGroupName: $(AzureResourceGroupName)
              azureLocation: $(AzureLocation)
              websitePassword: $(WebsitePassword)
              websiteSessionSecret: $(WebsiteSessionSecret)
              websiteName: $(WebsiteName)
              adoOrganizationUrl: $(System.CollectionUri)
              adoProjectName: $(System.TeamProject)
              adoRepositoryName: $(AdoRepositoryName)
              enableEntraIdAuth: $(EnableEntraIdAuth)
              entraIdTenantId: $(AzureTenantId)
              entraIdClientId: $(AzureClientId)
              entraIdClientSecret: $(AzureClientSecret)
              entraIdAllowedGroups: $(EntraIdAllowedGroups)
              disablePasswordAuth: $(DisablePasswordAuth)